# Generated by Django 2.2 on 2020-08-25 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('birth', models.DateField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('gender', models.CharField(choices=[('a', 'Male'), ('b', 'Female')], default='a', max_length=1)),
                ('workout_lvl', models.CharField(choices=[('1.2', 'sedentary (little to no exercise)'), ('1.375', 'lightly active (light exercise 1–3 days per week'), ('1.55', 'moderately active (moderate exercise 3–5 days per week'), ('1.725', 'very active (hard exercise 6–7 days per week'), ('1.9', 'extra active (very hard exercise, training, or a physical job')], default='a', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
